name: flutter_mapbox_autocomplete_plus
description: A Flutter Package for MapBox Places autocomplete which allows you use the MapBox API's to get autocomplete text of places
version: 2.3.0
publish_to: none
homepage: https://github.com/danbeyene/flutter_mapbox_autocomplete_plus

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  outline_gradient_button: ^2.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
